### ISSUE TITLE
Hates Macaws Furniture TFC.

### ISSUE THREAD

**Issue by MagmaSlime123** [Mrthomas20121-Mods/TFC-Decoration#4]
Title. The mod also hates TFC Rocks+ as well.

https://github.com/Mrthomas20121-Mods/TFC_rocksplus/issues/10.

**Comment by Mrthomas20121** [comment]
You need to fucking install not enough ids and just enough ids. Googling the error would have solved your issue.
LOOK UP THE ERROR ONLINE NEXT TIME BEFORE WASTING MY TIME WITH THIS CRAP
